name: space_traders
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: any
  freezed_annotation: any
  flutter_bloc: ^8.1.3
  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  build_runner: any
  freezed: any
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
