name: space_traders
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: any
  freezed_annotation: any
  flutter_bloc: ^8.1.6
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.0
  flutter_launcher_icons: ^0.13.1
  timezone: ^0.9.3
  awesome_notifications: ^0.10.1
  flutter_svg: ^2.0.10+1
  phosphor_flutter: ^2.1.0
  flutter_animate: ^4.5.0
  mockito: ^5.4.4
  freezed: ^3.2.3
  envied: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  build_runner: any
  envied_generator: ^1.3.0
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  image_path: "lib/assets/images/background.png"
  adaptive_icon_background: "lib/assets/images/background.png"
  adaptive_icon_foreground: "lib/assets/images/background.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
